# CSC Puhti
single-gpu-partition: gputest
multi-gpu-partition: gputest
cpu-partition: small # not test, that is charged by the node
cpu-account: project_2007095
gpu-account: project_2007095
time-limit: "00:15:00"
